# define gui constants
GAMESTATE_LOADING = 0
GAMESTATE_MENU = 1
GAMESTATE_INGAME = 2

PANEL_ANCHOR_NOT_SET = 0
PANEL_ANCHOR_TOP = 1
PANEL_ANCHOR_RIGHT = 2
PANEL_ANCHOR_BOTTOM = 3
PANEL_ANCHOR_LEFT = 4

PANEL_ALIGN_HORIZONTAL = 0
PANEL_ALIGN_VERTICAL = 1